name: Auto Pull Request - DEV to MAIN

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  auto-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sync branches
        uses: TreTuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: develop
          TO_BRANCH: main
          PULL_REQUEST_TITLE: "[Auto Create PR] Merge from Dev To MAIN"
